import { Lead } from './types';

export const mockLeads: Lead[] = [
  {
    id: 'L-001',
    companyName: 'Acme Corporation',
    contactName: 'Sarah Johnson',
    email: 'sarah.johnson@acme.com',
    phone: '+1 (555) 123-4567',
    status: 'qualified',
    source: 'linkedin',
    value: 45000,
    lastContact: new Date('2026-01-28'),
    createdAt: new Date('2026-01-15'),
    priority: 'high',
    notes: 'Interested in enterprise plan. Budget approved for Q1.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-002',
    companyName: 'TechStart Inc',
    contactName: 'Michael Chen',
    email: 'm.chen@techstart.io',
    phone: '+1 (555) 234-5678',
    status: 'proposal',
    source: 'website',
    value: 78000,
    lastContact: new Date('2026-01-29'),
    createdAt: new Date('2026-01-10'),
    priority: 'high',
    notes: 'Requested custom pricing. Decision maker meeting scheduled.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-003',
    companyName: 'Global Solutions Ltd',
    contactName: 'Emma Williams',
    email: 'ewilliams@globalsolutions.com',
    phone: '+1 (555) 345-6789',
    status: 'negotiation',
    source: 'referral',
    value: 125000,
    lastContact: new Date('2026-01-30'),
    createdAt: new Date('2025-12-20'),
    priority: 'high',
    notes: 'Contract review in progress. Negotiating implementation timeline.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-004',
    companyName: 'Innovate Labs',
    contactName: 'David Park',
    email: 'dpark@innovatelabs.com',
    phone: '+1 (555) 456-7890',
    status: 'contacted',
    source: 'cold-outreach',
    value: 32000,
    lastContact: new Date('2026-01-27'),
    createdAt: new Date('2026-01-22'),
    priority: 'medium',
    notes: 'Initial call completed. Sent product overview.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-005',
    companyName: 'Enterprise Dynamics',
    contactName: 'Lisa Martinez',
    email: 'lmartinez@entdynamics.com',
    phone: '+1 (555) 567-8901',
    status: 'closed-won',
    source: 'partner',
    value: 95000,
    lastContact: new Date('2026-01-25'),
    createdAt: new Date('2025-12-01'),
    priority: 'high',
    notes: 'Deal closed. Onboarding starts Feb 1.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-006',
    companyName: 'Velocity Systems',
    contactName: 'James Wilson',
    email: 'jwilson@velocitysys.com',
    phone: '+1 (555) 678-9012',
    status: 'new',
    source: 'website',
    value: 28000,
    lastContact: new Date('2026-01-30'),
    createdAt: new Date('2026-01-30'),
    priority: 'medium',
    notes: 'Just filled out contact form. Needs follow-up call.',
    ownerId: 'agent-2',
  },
  {
    id: 'L-007',
    companyName: 'CloudFirst Technologies',
    contactName: 'Rachel Green',
    email: 'rgreen@cloudfirst.tech',
    phone: '+1 (555) 789-0123',
    status: 'qualified',
    source: 'event',
    value: 56000,
    lastContact: new Date('2026-01-29'),
    createdAt: new Date('2026-01-18'),
    priority: 'high',
    notes: 'Met at SaaS Summit. Strong interest in platform integration.',
    ownerId: 'agent-2',
  },
  {
    id: 'L-008',
    companyName: 'Nexus Group',
    contactName: 'Tom Anderson',
    email: 'tanderson@nexusgroup.com',
    phone: '+1 (555) 890-1234',
    status: 'contacted',
    source: 'linkedin',
    value: 41000,
    lastContact: new Date('2026-01-26'),
    createdAt: new Date('2026-01-20'),
    priority: 'medium',
    notes: 'Discovery call scheduled for Feb 3.',
    ownerId: 'agent-2',
  },
  {
    id: 'L-009',
    companyName: 'Prime Innovations',
    contactName: 'Sophie Turner',
    email: 'sturner@primeinnovations.com',
    phone: '+1 (555) 901-2345',
    status: 'closed-lost',
    source: 'cold-outreach',
    value: 38000,
    lastContact: new Date('2026-01-24'),
    createdAt: new Date('2025-12-15'),
    priority: 'low',
    notes: 'Went with competitor. Price was main factor.',
    ownerId: 'agent-2',
  },
  {
    id: 'L-010',
    companyName: 'DataWise Corp',
    contactName: 'Kevin Brown',
    email: 'kbrown@datawise.com',
    phone: '+1 (555) 012-3456',
    status: 'proposal',
    source: 'referral',
    value: 67000,
    lastContact: new Date('2026-01-29'),
    createdAt: new Date('2026-01-12'),
    priority: 'high',
    notes: 'Proposal sent. Waiting for internal review.',
    ownerId: 'agent-2',
  },
  {
    id: 'L-011',
    companyName: 'Stellar Industries',
    contactName: 'Anna Davis',
    email: 'adavis@stellarind.com',
    phone: '+1 (555) 123-7890',
    status: 'new',
    source: 'website',
    value: 22000,
    lastContact: new Date('2026-01-30'),
    createdAt: new Date('2026-01-30'),
    priority: 'low',
    notes: 'Downloaded whitepaper. Potential small business customer.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-012',
    companyName: 'Quantum Ventures',
    contactName: 'Robert Lee',
    email: 'rlee@quantumvc.com',
    phone: '+1 (555) 234-8901',
    status: 'qualified',
    source: 'partner',
    value: 89000,
    lastContact: new Date('2026-01-28'),
    createdAt: new Date('2026-01-14'),
    priority: 'high',
    notes: 'Partner referral. Needs multi-year contract.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-013',
    companyName: 'Apex Solutions',
    contactName: 'Jennifer White',
    email: 'jwhite@apexsolutions.net',
    phone: '+1 (555) 345-9012',
    status: 'negotiation',
    source: 'event',
    value: 103000,
    lastContact: new Date('2026-01-29'),
    createdAt: new Date('2026-01-05'),
    priority: 'high',
    notes: 'Legal reviewing terms. Close expected in 2 weeks.',
    ownerId: 'agent-1',
  },
  {
    id: 'L-014',
    companyName: 'Fusion Digital',
    contactName: 'Chris Martinez',
    email: 'cmartinez@fusiondigital.io',
    phone: '+1 (555) 456-0123',
    status: 'contacted',
    source: 'linkedin',
    value: 35000,
    lastContact: new Date('2026-01-25'),
    createdAt: new Date('2026-01-19'),
    priority: 'medium',
    notes: 'Initial outreach positive. Demo requested.',
    ownerId: 'agent-2',
  },
  {
    id: 'L-015',
    companyName: 'Horizon Enterprises',
    contactName: 'Monica Taylor',
    email: 'mtaylor@horizonent.com',
    phone: '+1 (555) 567-1234',
    status: 'closed-won',
    source: 'referral',
    value: 72000,
    lastContact: new Date('2026-01-23'),
    createdAt: new Date('2025-11-28'),
    priority: 'high',
    notes: 'Successfully closed. Implementation in progress.',
    ownerId: 'agent-2',
  },
];
